title: "Honkai: Star Rail Lore Compendium"
description: "A fan-made lore compendium for Honkai: Star Rail"
plugins:
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-titles-from-headings
include:
  - README.md
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
